### ISSUE TITLE
Use GitHub Releases page for release notes?

### ISSUE THREAD

**Issue by bgrainger** [Faithlife/FaithlifeUtility#14]
Should we change https://github.com/Faithlife/FaithlifeUtility/blob/a051b2a6765bf87e2b4be985af316d329bcebafb/src/Faithlife.Utility/Faithlife.Utility.csproj#L14 from https://github.com/Faithlife/FaithlifeUtility/blob/master/VersionHistory.md#released to https://github.com/Faithlife/FaithlifeUtility/releases ?

### Benefits

* Looks better (maybe)
* Shorter URL
* Can be edited without having to push to the repo

### Cons

* Must be manually kept in sync with `VersionHistory.md`
* Can be edited without having to push to the repo
* Has "Downloads" links that are irrelevant/misleading; users should be pointed to NuGet instead of downloading a source tarball

**Comment by ejball** [comment]
Seems better as-is.
