### ISSUE TITLE
Remove DictionaryUtility.GetValueOrDefault() and TryAdd().

### ISSUE THREAD

**Issue by ddunkin** [Faithlife/FaithlifeUtility#19]
They conflict with equivalents in .NET Core 2.0:
* [GetValueOrDefault](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.collectionextensions.getvalueordefault?view=netcore-2.0)
* [TryAdd](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.collectionextensions.tryadd?view=netcore-2.0)

**Comment by StephenCleary** [comment]
`CollectionExtensions` appears to be for .NET Core only, not netstandard. So I think it would be useful to include them for netstandard, but consider adding a netcore build without them.

**Comment by ejball** [comment]
Ick. What namespace/assembly is it in?

**Comment by ddunkin** [comment]
If the method exists in the netstandard build but not in the netcore build, won't another netstandard library compiled against netstandard Faithlife.Utility fail with a missing method error if run on netcore?

**Comment by ddunkin** [comment]
The least worst workaround I've found is to not call methods like these as extension methods. Maybe we keep the methods in Faithlife.Utility but not as extension methods?

**Comment by ejball** [comment]
What if we kept them in the netcore build but made them not extension methods there?

**Comment by ejball** [comment]
Or we could define our own `System.Collections.Generic.CollectionExtensions` and forward it in the netcore build?

**Comment by ddunkin** [comment]
> What if we kept them in the netcore build but made them not extension methods there?

Yeah, I was wondering about that. Need to check if the extension method metadata affects method resolution.

**Comment by ddunkin** [comment]
This may also be an issue for Xamarin targets.

**Comment by bgrainger** [comment]
These methods [are in `netstandard2.1`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.collectionextensions.getvalueordefault?view=netstandard-2.1) so this is going to start becoming more of an issue.

**Comment by bgrainger** [comment]
I think we can fix it with Dave's PR by adding targets for `netcoreapp2.0` and `netstandard2.1`?
