### ISSUE TITLE
Lowercase booleans in UriUtility.FromPattern().

### ISSUE THREAD

**Issue by ddunkin** [Faithlife/FaithlifeUtility#23]
`UriUtility.FromPattern()` serializes values using `Convert.ToString(value, CultureInfo.InvariantCulture)`. Booleans are serialized `"True"` or `"False"`. .NET will parse those values correctly, but other platforms will not, including Java and Ruby on Rails.

Booleans should be serialized as `"true"` or `"false"` for better compatibility with more platforms.

**Comment by ejball** [comment]
FWIW, `InvariantConvert.ToInvariantString` from this library does just that.
