### ISSUE TITLE
Obsolete TakeLast

### ISSUE THREAD

**Issue by ddunkin** [Faithlife/FaithlifeUtility#40]
In .NET Standard 2.1, use [Enumerable.TakeLast](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.takelast?view=netstandard-2.1).

**Comment by bgrainger** [comment]
In .NET 6, use [`Take(Range)`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.take?view=net-6.0#System_Linq_Enumerable_Take__1_System_Collections_Generic_IEnumerable___0__System_Range_).
